version: '3'
services:
  vue-client:
    build: ./client
    command: bash -c "npm install && npm run dev"
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0

  node-server:
    build: ./server
    command: bash -c "npm install && npm run serve"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DB_URL=mongodb://mongo:27017/userdb
    ports:
      - "9000:9000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./tmp/data:/data/db
    ports:
      - "27017:27017" 